---
- hosts: localhost
  tasks:
  - name: post to consu
    shell: 'curl --request POST --header "PRIVATE-TOKEN: T4yQ4kDa2iYyiQ4zZGb7" --data "name="{{ item.name }}"&user_id="{{ item.user_id }}"&access_level="{{ item.access_level }}"" http://35.196.172.176/api/v4/groups/"{{ item.group }}"/members'
    with_items:
      - { name: user9 , user_id: 11 , access_level: 30 , group: Sonic_Group }
     
